name: live_uttarakhand
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  html: ^0.15.5
  flutter_html: ^3.0.0

  xml: ^6.5.0

  flutter_localizations:
    sdk: flutter
  package_info_plus: ^8.3.0
  nb_utils: ^6.1.3
  google_fonts: ^6.2.1
  flutter_vector_icons: ^2.0.0
  fading_edge_scrollview: ^4.1.1
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  story_view: ^0.16.5
  rive: ^0.13.20
  clippy_flutter: ^2.0.0-nullsafety.1
  video_player: ^2.9.5
  http: ^1.3.0
  intl: ^0.18.1
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  onesignal_flutter: ^5.3.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.5.2
  firebase_remote_config: ^5.4.3
  firebase_crashlytics: ^4.3.5
  facebook_audience_network: ^1.0.1
  google_sign_in: ^6.3.0
  otp_text_field: ^1.1.3
  country_code_picker: ^3.3.0
  the_apple_sign_in: ^1.1.1
  cached_network_image: ^3.4.1
  geolocator: ^13.0.4
  flutter_tts: ^4.2.2
  image_picker: ^1.1.2
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  flutter_svg: ^1.1.6
  connectivity_plus: ^5.0.2
  ffi: ^2.1.4
  provider: ^6.1.4
  image: ^4.5.4
  youtube_player_flutter: ^9.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.2
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0

  #flutter packages pub run build_runner build --delete-conflicting-outputs
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
dependency_overrides:
  intl: ^0.18.1
  xml: ^6.2.2
  html: ^0.15.4
  webview_flutter: ^4.8.0
  nb_utils: ^6.0.6
  flutter_math_fork: ^0.7.2
  flutter_svg: ^1.0.0
  flutter_layout_grid: ^2.0.7
  connectivity_plus: ^5.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/flags/
    - lang/
    - assets/rive/